import csv
import gc
import json
import os
import shutil
import shlex
import subprocess
import sys
from collections import Counter
from datetime import datetime
from pathlib import Path
from typing import Any

import numpy as np
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

# Ensure local project code is imported when launched as `torchrun nl_probes/sft_trainer.py`.
PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import torch
from transformers import Trainer
from transformers.trainer import TRAINING_ARGS_NAME

from nl_probes.dataset_classes.custom_pt_dataset import TransformedTrainingDataPointDataset
from nl_probes.utils.common import (
    load_tokenizer,
    maybe_save_dynamic_model_code,
    set_seed,
    temporarily_disable_generation_parameter_validation,
)
from nl_probes.utils.activation_oracle_cli import (
    parse_cli_args,
    resolve_best_model_selection as _resolve_best_model_selection,
)
from nl_probes.utils.activation_oracle_data_pipeline import prepare_datasets
from nl_probes.utils.activation_oracle_modeling import (
    build_activation_oracle_model as _build_activation_oracle_model,
    build_training_args as _build_training_args,
)
from nl_probes.utils.activation_oracle_runtime import (
    ActivationOracleBatchCollator,
    ActivationOracleWrapper,
)
from nl_probes.utils.dataset_utils import (
    TrainingDataPoint,
    get_prompt_tokens_only,
)
from nl_probes.utils.eval import (
    log_metrics_to_wandb,
    run_evaluation,
)
from nl_probes.utils.safety_task_spec import (
    build_safety_eval_spec,
    compute_safety_generation_metrics,
    print_generation_debug_samples as _print_generation_debug_samples,
    print_safety_label_distribution,
    print_supervised_token_distribution as _print_supervised_token_distribution,
    print_training_target_distribution as _print_training_target_distribution,
    summarize_training_dataset as _summarize_training_dataset,
)

def _local_rank() -> int:
    return int(os.environ.get("LOCAL_RANK", "0"))


def _world_size() -> int:
    return int(os.environ.get("WORLD_SIZE", "1"))


def _is_local_rank_zero() -> bool:
    return _local_rank() == 0


def _get_training_command() -> str:
    raw_argv = getattr(sys, "orig_argv", None) or [sys.executable, *sys.argv]
    argv = [str(arg) for arg in raw_argv if arg is not None]
    if os.name == "nt":
        return subprocess.list2cmdline(argv)
    return shlex.join(argv)


def _write_training_command_script(output_dir: str | Path, training_command: str) -> Path:
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    script_path = output_path / "train_command.sh"
    launch_cwd = Path.cwd().resolve()
    script_lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Auto-generated by nl_probes/sft_trainer.py",
        f"# Generated at: {datetime.now().astimezone().isoformat(timespec='seconds')}",
        f"# Original working directory: {launch_cwd}",
        "",
        f"cd {shlex.quote(str(launch_cwd))}",
        training_command,
        "",
    ]
    script_path.write_text("\n".join(script_lines), encoding="utf-8")
    script_path.chmod(script_path.stat().st_mode | 0o111)
    return script_path


def _dist_is_initialized() -> bool:
    return torch.distributed.is_available() and torch.distributed.is_initialized()


def _sanitize_metric_key(key: str) -> str:
    sanitized = "".join(char if char.isalnum() else "_" for char in str(key))
    while "__" in sanitized:
        sanitized = sanitized.replace("__", "_")
    return sanitized.strip("_")


def _coerce_metric_value(value: Any) -> int | float | str | None:
    if value is None:
        return None
    if isinstance(value, (np.integer, int)) and not isinstance(value, bool):
        return int(value)
    if isinstance(value, (np.floating, float)):
        return float(value)
    if isinstance(value, bool):
        return int(value)
    if isinstance(value, str):
        return value
    return str(value)


def _format_named_eval_metrics(
    metric_key_prefix: str,
    dataset_name: str,
    metrics: dict[str, Any],
) -> dict[str, int | float | str | None]:
    formatted: dict[str, int | float | str | None] = {}
    prefix = _sanitize_metric_key(metric_key_prefix)
    dataset = _sanitize_metric_key(dataset_name)
    for raw_key, raw_value in metrics.items():
        metric_name = raw_key.split("/", 1)[1] if isinstance(raw_key, str) and "/" in raw_key else str(raw_key)
        column_name = "_".join(part for part in (prefix, dataset, _sanitize_metric_key(metric_name)) if part)
        formatted[column_name] = _coerce_metric_value(raw_value)
    return formatted


def _resolve_effective_hook_layer(
    hook_layer: int | str,
    layer_counts: Counter[int],
    auto_match_hook_layer: bool,
) -> int | str:
    if not isinstance(hook_layer, int):
        return hook_layer

    print(f"Training data layer distribution: {dict(sorted(layer_counts.items()))}")
    if not layer_counts:
        return hook_layer

    unique_layers = sorted(layer_counts.keys())
    if len(unique_layers) == 1 and hook_layer != unique_layers[0]:
        data_layer = unique_layers[0]
        if auto_match_hook_layer:
            print(f"Auto-matching hook layer: {hook_layer} -> {data_layer}")
            return data_layer
    return hook_layer


class ActivationOracleTrainer(Trainer):
    def __init__(
        self,
        *args,
        generation_eval_datasets: dict[str, Any] | None = None,
        generation_eval_batch_size: int = 8,
        generation_kwargs: dict[str, Any] | None = None,
        generation_debug_max_examples: int = 0,
        training_command: str | None = None,
        **kwargs,
    ) -> None:
        super().__init__(*args, **kwargs)
        self.model_accepts_loss_kwargs = False
        self.generation_eval_datasets = generation_eval_datasets or {}
        self.generation_eval_batch_size = generation_eval_batch_size
        self.generation_kwargs = generation_kwargs or {"do_sample": False, "max_new_tokens": 128}
        self.generation_debug_max_examples = generation_debug_max_examples
        self.prompt_only_generation_eval_datasets = {
            dataset_name: TransformedTrainingDataPointDataset(dataset_points, get_prompt_tokens_only)
            for dataset_name, dataset_points in self.generation_eval_datasets.items()
        }
        self.generation_eval_specs = {
            dataset_name: build_safety_eval_spec(dataset_points)
            for dataset_name, dataset_points in self.generation_eval_datasets.items()
        }
        run_started_at = datetime.now().astimezone()
        run_started_tag = run_started_at.strftime("%Y%m%d_%H%M%S_%f")
        self.run_started_at = run_started_at.isoformat(timespec="seconds")
        self.training_command = training_command.strip() if training_command and training_command.strip() else None
        self.eval_metrics_csv_path = Path(self.args.output_dir) / f"eval_metrics_{run_started_tag}.csv"
        self.best_eval_json_path = Path(self.args.output_dir) / "best.json"
        self.best_model_dir_path = Path(self.args.output_dir) / "best"
        self.best_model_info_path = Path(self.args.output_dir) / "best_model_info.json"
        self.eval_metrics_history: list[dict[str, int | float | str | None]] = []
        self.best_macro_f1: float | None = None
        os.makedirs(self.args.output_dir, exist_ok=True)
        self.training_command_script_path: Path | None = None
        if self.training_command is not None and self.is_world_process_zero():
            self.training_command_script_path = _write_training_command_script(
                self.args.output_dir,
                self.training_command,
            )

    def _write_eval_metrics_csv(self) -> None:
        field_priority = [
            "run_started_at",
            "logged_at",
            "metric_key_prefix",
            "step",
            "epoch",
            "tracked_macro_f1",
            "tracked_macro_f1_source",
        ]
        fieldnames = list(field_priority)
        for row in self.eval_metrics_history:
            for key in row:
                if key not in fieldnames:
                    fieldnames.append(key)

        with self.eval_metrics_csv_path.open("w", newline="", encoding="utf-8") as csv_file:
            writer = csv.DictWriter(csv_file, fieldnames=fieldnames, extrasaction="ignore")
            writer.writeheader()
            for row in self.eval_metrics_history:
                writer.writerow(row)

    def _update_best_eval_json(self, row: dict[str, int | float | str | None]) -> None:
        tracked_macro_f1 = row.get("tracked_macro_f1")
        if tracked_macro_f1 is None:
            return

        tracked_macro_f1_value = float(tracked_macro_f1)
        if self.best_macro_f1 is not None and tracked_macro_f1_value <= self.best_macro_f1:
            return

        self.best_macro_f1 = tracked_macro_f1_value
        payload = dict(row)
        payload["best_updated_at"] = datetime.now().astimezone().isoformat(timespec="seconds")
        if self.training_command is not None:
            payload["training_command"] = self.training_command
        with self.best_eval_json_path.open("w", encoding="utf-8") as json_file:
            json.dump(payload, json_file, indent=2, ensure_ascii=False)

    def _append_eval_metrics_row(
        self,
        *,
        metric_key_prefix: str,
        metrics: dict[str, Any],
        extra_metrics: dict[str, Any] | None = None,
    ) -> None:
        row: dict[str, int | float | str | None] = {
            "run_started_at": self.run_started_at,
            "logged_at": datetime.now().astimezone().isoformat(timespec="seconds"),
            "metric_key_prefix": metric_key_prefix,
            "step": int(self.state.global_step),
            "epoch": _coerce_metric_value(metrics.get("epoch", self.state.epoch)),
        }
        for raw_key, raw_value in metrics.items():
            row[_sanitize_metric_key(raw_key)] = _coerce_metric_value(raw_value)
        for raw_key, raw_value in (extra_metrics or {}).items():
            row[_sanitize_metric_key(raw_key)] = _coerce_metric_value(raw_value)

        macro_f1_candidates = [
            (key, float(value))
            for key, value in row.items()
            if key.endswith("macro_f1") and value is not None
        ]
        if macro_f1_candidates:
            tracked_source, tracked_value = max(macro_f1_candidates, key=lambda item: item[1])
            row["tracked_macro_f1_source"] = tracked_source
            row["tracked_macro_f1"] = tracked_value

        self.eval_metrics_history.append(row)
        self._write_eval_metrics_csv()
        self._update_best_eval_json(row)

    def _get_metric_for_best_model_key(self) -> str | None:
        metric_for_best_model = self.args.metric_for_best_model
        if metric_for_best_model is None:
            return None
        if metric_for_best_model.startswith("eval_"):
            return metric_for_best_model
        return f"eval_{metric_for_best_model}"

    def _save_best_model_snapshot(self, metrics: dict[str, float]) -> None:
        metric_key = self._get_metric_for_best_model_key()
        if metric_key is None:
            return

        metric_value = metrics.get(metric_key)
        self.save_model_only(str(self.best_model_dir_path))

        if not self.is_world_process_zero():
            return

        payload: dict[str, int | float | str | None] = {
            "metric_for_best_model": metric_key,
            "best_metric": float(metric_value) if metric_value is not None else None,
            "global_step": int(self.state.global_step),
            "epoch": _coerce_metric_value(self.state.epoch),
            "saved_at": datetime.now().astimezone().isoformat(timespec="seconds"),
            "best_global_step": int(self.state.best_global_step) if self.state.best_global_step is not None else None,
            "model_dir": str(self.best_model_dir_path),
        }
        if self.training_command is not None:
            payload["training_command"] = self.training_command
        with self.best_model_info_path.open("w", encoding="utf-8") as json_file:
            json.dump(payload, json_file, indent=2, ensure_ascii=False)
        print(
            f"Saved new best model to: {self.best_model_dir_path} "
            f"({metric_key}={metric_value}, step={self.state.global_step})"
        )

    def _determine_best_metric(self, metrics: dict[str, float], trial=None) -> bool:
        is_new_best_metric = super()._determine_best_metric(metrics=metrics, trial=trial)
        if is_new_best_metric:
            self._save_best_model_snapshot(metrics)
        return is_new_best_metric

    def evaluate(
        self,
        eval_dataset=None,
        ignore_keys: list[str] | None = None,
        metric_key_prefix: str = "eval",
    ) -> dict[str, float]:
        was_training = self.model.training
        metrics = {}
        extra_eval_metrics: dict[str, Any] = {}
        if eval_dataset is not None or self.eval_dataset is not None:
            metrics.update(
                super().evaluate(
                    eval_dataset=eval_dataset,
                    ignore_keys=ignore_keys,
                    metric_key_prefix=metric_key_prefix,
                )
            )
        if not self.generation_eval_datasets:
            if self.is_world_process_zero() and metrics:
                self._append_eval_metrics_row(metric_key_prefix=metric_key_prefix, metrics=metrics)
            if was_training:
                self.model.train()
            return metrics

        model_to_eval = self.accelerator.unwrap_model(self.model)
        if not isinstance(model_to_eval, ActivationOracleWrapper):
            raise TypeError(f"Expected ActivationOracleWrapper, got {type(model_to_eval).__name__}")

        base_model = model_to_eval.base_model
        hook_submodule = model_to_eval.hook_submodule
        device = self.args.device
        hook_dtype = model_to_eval.hook_dtype

        base_model.eval()
        generation_metrics = {}

        grad_ckpt_was_enabled = bool(getattr(base_model, "is_gradient_checkpointing", False))
        prev_model_use_cache = getattr(base_model.config, "use_cache", None)
        prev_generation_use_cache = getattr(getattr(base_model, "generation_config", None), "use_cache", None)
        nested_language_model = getattr(getattr(base_model, "model", None), "language_model", None)
        prev_nested_use_cache = getattr(getattr(nested_language_model, "config", None), "use_cache", None)

        try:
            if grad_ckpt_was_enabled and hasattr(base_model, "gradient_checkpointing_disable"):
                base_model.gradient_checkpointing_disable()
            if prev_model_use_cache is not None:
                base_model.config.use_cache = True
            if getattr(base_model, "generation_config", None) is not None and prev_generation_use_cache is not None:
                base_model.generation_config.use_cache = True
            if nested_language_model is not None and prev_nested_use_cache is not None:
                nested_language_model.config.use_cache = True

            for dataset_name, dataset_points in self.generation_eval_datasets.items():
                eval_responses = run_evaluation(
                    eval_data=self.prompt_only_generation_eval_datasets[dataset_name],
                    model=base_model,
                    tokenizer=self.processing_class,
                    submodule=hook_submodule,
                    device=device,
                    dtype=hook_dtype,
                    global_step=self.state.global_step,
                    lora_path=None,
                    eval_batch_size=self.generation_eval_batch_size,
                    steering_coefficient=model_to_eval.steering_coefficient,
                    steering_mode=model_to_eval.steering_mode,
                    generation_kwargs=self.generation_kwargs,
                    prompt_only_inputs=True,
                    distributed=True,
                    auto_log_binary_safety_metrics=False,
                )
                if self.is_world_process_zero():
                    dataset_metrics = compute_safety_generation_metrics(
                        eval_responses,
                        dataset_points,
                        self.generation_eval_specs[dataset_name],
                    )
                    generation_metrics.update(
                        _format_named_eval_metrics(
                            metric_key_prefix,
                            dataset_name,
                            dataset_metrics,
                        )
                    )
                    print(
                        f"Step {self.state.global_step} {dataset_name} "
                        f"safety_macro_f1={dataset_metrics.get('safety_macro_f1', 0.0):.4f} "
                        f"parent_macro_f1={dataset_metrics.get('parent_macro_f1', 0.0):.4f} "
                        f"subcategory_macro_f1={dataset_metrics.get('subcategory_macro_f1', 0.0):.4f}"
                    )
                    _print_generation_debug_samples(
                        eval_responses,
                        dataset_points,
                        eval_spec=self.generation_eval_specs[dataset_name],
                        max_examples=self.generation_debug_max_examples,
                    )
        finally:
            if prev_model_use_cache is not None:
                base_model.config.use_cache = prev_model_use_cache
            if getattr(base_model, "generation_config", None) is not None and prev_generation_use_cache is not None:
                base_model.generation_config.use_cache = prev_generation_use_cache
            if nested_language_model is not None and prev_nested_use_cache is not None:
                nested_language_model.config.use_cache = prev_nested_use_cache
            if grad_ckpt_was_enabled and hasattr(base_model, "gradient_checkpointing_enable"):
                base_model.gradient_checkpointing_enable()

        if _dist_is_initialized():
            metrics_payload = [generation_metrics if self.is_world_process_zero() else None]
            torch.distributed.broadcast_object_list(metrics_payload, src=0)
            generation_metrics = metrics_payload[0] or {}
            extra_metrics_payload = [extra_eval_metrics if self.is_world_process_zero() else None]
            torch.distributed.broadcast_object_list(extra_metrics_payload, src=0)
            extra_eval_metrics = extra_metrics_payload[0] or {}

        if self.is_world_process_zero():
            logged_metrics = dict(generation_metrics)
            logged_metrics.update(extra_eval_metrics)
            if logged_metrics:
                self.log(logged_metrics)
                log_metrics_to_wandb(
                    metrics=logged_metrics,
                    global_step=self.state.global_step,
                    source_step_key=f"{metric_key_prefix}_generation_source_step",
                    only_on_step_adjustment=True,
                )

        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        gc.collect()

        if was_training:
            self.model.train()
        metrics.update(generation_metrics)
        metrics.update(extra_eval_metrics)
        if self.is_world_process_zero() and metrics:
            self._append_eval_metrics_row(metric_key_prefix=metric_key_prefix, metrics=metrics)
        return metrics

    def _base_model_state_dict(
        self,
        state_dict: dict[str, torch.Tensor] | None,
    ) -> dict[str, torch.Tensor] | None:
        if state_dict is None:
            return None

        wrapper_prefixes = ("base_model.", "module.base_model.")
        for prefix in wrapper_prefixes:
            stripped = {
                key[len(prefix):]: value
                for key, value in state_dict.items()
                if key.startswith(prefix)
            }
            if stripped:
                return stripped
        return state_dict

    def save_model_only(self, output_dir: str | Path) -> None:
        output_path = Path(output_dir)
        if self.is_world_process_zero() and output_path.exists():
            shutil.rmtree(output_path)
        if _dist_is_initialized():
            torch.distributed.barrier()
        self.save_model(str(output_path))
        if _dist_is_initialized():
            torch.distributed.barrier()

    def _save(self, output_dir: str | None = None, state_dict: dict[str, torch.Tensor] | None = None) -> None:
        output_dir = output_dir or self.args.output_dir
        os.makedirs(output_dir, exist_ok=True)
        model_to_save = self.accelerator.unwrap_model(self.model)

        if not isinstance(model_to_save, ActivationOracleWrapper):
            super()._save(output_dir=output_dir, state_dict=state_dict)
            return

        save_kwargs: dict[str, Any] = {"safe_serialization": True}
        base_state_dict = self._base_model_state_dict(state_dict)
        if base_state_dict is not None:
            save_kwargs["state_dict"] = base_state_dict
        with temporarily_disable_generation_parameter_validation(getattr(model_to_save.base_model, "config", None)):
            model_to_save.base_model.save_pretrained(output_dir, **save_kwargs)
        maybe_save_dynamic_model_code(model_to_save.base_model, output_dir)
        if self.processing_class is not None:
            self.processing_class.save_pretrained(output_dir)
        torch.save(self.args, os.path.join(output_dir, TRAINING_ARGS_NAME))


def _run_single_model(model_name: str) -> None:
    dtype = torch.bfloat16
    set_seed(cli_args.seed)

    world_size = _world_size()
    if cli_args.global_train_batch_size % world_size != 0:
        raise ValueError(
            f"Global batch size {cli_args.global_train_batch_size} must be divisible by world_size {world_size}"
        )

    per_device_train_batch_size = cli_args.global_train_batch_size // world_size
    if cli_args.global_eval_batch_size > 0:
        if cli_args.global_eval_batch_size % world_size != 0:
            raise ValueError(
                f"Global eval batch size {cli_args.global_eval_batch_size} must be divisible by world_size {world_size}"
            )
        per_device_eval_batch_size = cli_args.global_eval_batch_size // world_size
    else:
        per_device_eval_batch_size = per_device_train_batch_size * 8

    if cli_args.generation_eval_batch_size > 0:
        generation_eval_batch_size = cli_args.generation_eval_batch_size
    else:
        generation_eval_batch_size = per_device_eval_batch_size

    effective_global_update_batch_size = cli_args.global_train_batch_size * cli_args.gradient_accumulation_steps
    effective_per_device_update_batch_size = per_device_train_batch_size * cli_args.gradient_accumulation_steps

    print(
        "Global train batch size per micro-step "
        f"(all ranks, before gradient accumulation): {cli_args.global_train_batch_size}"
    )
    print(
        f"Per-device train micro-batch size: {per_device_train_batch_size}, "
        f"world size: {world_size}"
    )
    print(f"Gradient accumulation steps: {cli_args.gradient_accumulation_steps}")
    print(
        "Effective train batch size per optimizer update "
        f"(all ranks): {effective_global_update_batch_size}"
    )
    print(
        "Effective per-device samples contributing to each optimizer update: "
        f"{effective_per_device_update_batch_size}"
    )
    print(f"Per-device teacher-forced eval batch size: {per_device_eval_batch_size}")
    print(f"Per-rank generation eval batch size: {generation_eval_batch_size}")

    tokenizer = load_tokenizer(model_name)
    dataset_bundle = prepare_datasets(
        model_name=model_name,
        tokenizer=tokenizer,
        train_pt_path=cli_args.custom_train_pt_path,
        test_pt_path=cli_args.custom_test_pt_path,
        max_train_records=cli_args.max_train_examples,
        max_eval_records=cli_args.max_eval_examples,
        max_seq_length=cli_args.max_seq_length,
    )
    training_data = dataset_bundle.training_data
    eval_datasets = dataset_bundle.eval_datasets
    if dataset_bundle.train_filter_stats is not None:
        train_filter_stats = dataset_bundle.train_filter_stats
        eval_filter_stats = dataset_bundle.eval_filter_stats or {}
        if _is_local_rank_zero():
            print(
                f"Applied --max-seq-length={cli_args.max_seq_length}: "
                f"train kept {train_filter_stats.kept_count}/{train_filter_stats.original_count} "
                f"(dropped {train_filter_stats.dropped_count}), "
                f"max_kept_length={train_filter_stats.max_kept_length}, "
                f"max_dropped_length={train_filter_stats.max_dropped_length}"
            )
            for dataset_name, filter_stats in eval_filter_stats.items():
                print(
                    f"  eval[{dataset_name}] kept {filter_stats.kept_count}/{filter_stats.original_count} "
                    f"(dropped {filter_stats.dropped_count}), "
                    f"max_kept_length={filter_stats.max_kept_length}, "
                    f"max_dropped_length={filter_stats.max_dropped_length}"
                )
    training_summary = _summarize_training_dataset(training_data)
    total_eval_examples = sum(len(dataset_points) for dataset_points in eval_datasets.values())
    print(f"training data length: {len(training_data)}, eval example count: {total_eval_examples}")
    if _is_local_rank_zero():
        _print_training_target_distribution(training_summary.answer_text_counts)
        _print_supervised_token_distribution(training_summary.supervised_len_counts)
        print_safety_label_distribution(
            training_summary.safety_label_counts,
            training_summary.unsafe_parent_category_counts,
        )
        print("Using standard causal-LM SFT loss over the full supervised answer span.")

    effective_hook_layer = _resolve_effective_hook_layer(
        cli_args.hook_layer,
        training_summary.layer_counts,
        cli_args.auto_match_hook_layer,
    )
    if effective_hook_layer != cli_args.hook_layer:
        print(f"Using effective hook layer: {effective_hook_layer}")
    elif _is_local_rank_zero() and isinstance(cli_args.hook_layer, int) and training_summary.layer_counts:
        unique_layers = sorted(training_summary.layer_counts.keys())
        if len(unique_layers) == 1 and cli_args.hook_layer != unique_layers[0]:
            print(
                "Hook layer differs from PT extraction layer: "
                f"hook_layer={cli_args.hook_layer}, pt_layer={unique_layers[0]}. "
                "This is allowed as long as the target layer hidden size matches the stored activations."
            )

    if _is_local_rank_zero():
        print(
            "PT dataset loading mode: "
            f"train={type(training_data).__name__}, "
            f"eval={[type(dataset_points).__name__ for dataset_points in eval_datasets.values()]}"
        )

    model = _build_activation_oracle_model(
        model_name=model_name,
        hook_layer=effective_hook_layer,
        dtype=dtype,
        gradient_checkpointing=cli_args.gradient_checkpointing,
        use_lora=cli_args.use_lora,
        lora_r=cli_args.lora_r,
        lora_alpha=cli_args.lora_alpha,
        lora_dropout=cli_args.lora_dropout,
        lora_target_modules=cli_args.lora_target_modules,
        load_lora_path=cli_args.load_lora_path,
        steering_coefficient=cli_args.steering_coefficient,
        steering_mode=cli_args.steering_mode,
    )

    model_name_str = model_name.split("/")[-1].replace(".", "_").replace(" ", "_")
    run_name = cli_args.wandb_run_name or f"trainer_custom_pt_{model_name_str}"
    metric_for_best_model = None
    greater_is_better = None
    if cli_args.save_best_model_at_end or cli_args.metric_for_best_model.strip():
        metric_for_best_model, greater_is_better = _resolve_best_model_selection(
            cli_args.metric_for_best_model,
            cli_args.greater_is_better,
        )
        if _is_local_rank_zero():
            comparison_text = "max" if greater_is_better else "min"
            print(
                "Best-model tracking enabled: "
                f"metric={metric_for_best_model}, mode={comparison_text}, "
                f"model_dir={Path(cli_args.save_dir) / 'best'}"
            )

    training_args = _build_training_args(
        save_dir=cli_args.save_dir,
        run_name=run_name,
        per_device_train_batch_size=per_device_train_batch_size,
        per_device_eval_batch_size=per_device_eval_batch_size,
        gradient_accumulation_steps=cli_args.gradient_accumulation_steps,
        lr=cli_args.lr,
        lr_scheduler_type=cli_args.lr_scheduler_type,
        warmup_ratio=cli_args.warmup_ratio,
        warmup_steps=cli_args.warmup_steps,
        num_epochs=cli_args.num_epochs,
        max_steps=cli_args.max_steps,
        max_grad_norm=cli_args.max_grad_norm,
        eval_steps=cli_args.eval_steps,
        eval_on_start=cli_args.eval_on_start,
        save_checkpoints=cli_args.save_checkpoints,
        use_deepspeed=cli_args.use_deepspeed,
        deepspeed_config_path=cli_args.deepspeed_config_path,
        dtype=dtype,
        use_lora=cli_args.use_lora,
        load_lora_path=cli_args.load_lora_path,
        model_name=model_name,
        report_to_wandb=cli_args.report_to_wandb,
        wandb_project=cli_args.wandb_project,
        has_eval_dataset=bool(eval_datasets),
        save_steps=cli_args.save_steps,
        save_best_model_at_end=cli_args.save_best_model_at_end,
        metric_for_best_model=metric_for_best_model,
        greater_is_better=greater_is_better,
        save_total_limit=cli_args.save_total_limit or None,
        seed=cli_args.seed,
        gradient_checkpointing=cli_args.gradient_checkpointing,
    )

    trainer = ActivationOracleTrainer(
        model=model,
        args=training_args,
        train_dataset=training_data,
        eval_dataset=next(iter(eval_datasets.values())) if eval_datasets else None,
        data_collator=ActivationOracleBatchCollator(tokenizer),
        processing_class=tokenizer,
        generation_eval_datasets=eval_datasets if cli_args.generation_eval else {},
        generation_eval_batch_size=generation_eval_batch_size,
        generation_kwargs={
            "do_sample": False,
            "max_new_tokens": cli_args.generation_max_new_tokens,
        },
        generation_debug_max_examples=cli_args.generation_debug_max_examples,
        training_command=_get_training_command(),
    )
    if trainer.is_world_process_zero():
        print(f"Eval metrics CSV will be written to: {trainer.eval_metrics_csv_path}")
        print(f"Best eval row JSON will be written to: {trainer.best_eval_json_path}")
        if trainer.training_command_script_path is not None:
            print(f"Training command script will be written to: {trainer.training_command_script_path}")

    trainer.train()
    if trainer.is_world_process_zero() and cli_args.save_best_model_at_end:
        print(f"Best Trainer checkpoint: {trainer.state.best_model_checkpoint}")
        print(f"Best Trainer metric: {trainer.state.best_metric}")

    post_train_metrics = None
    if cli_args.save_best_model_at_end and eval_datasets:
        post_train_metrics = trainer.evaluate(metric_key_prefix="eval")
        if trainer.is_world_process_zero():
            print(post_train_metrics)

    if cli_args.save_final_model:
        final_dir = Path(cli_args.save_dir) / "final"
        trainer.save_model_only(str(final_dir))

    if eval_datasets:
        final_metrics = post_train_metrics
        if final_metrics is None:
            final_metrics = trainer.evaluate(metric_key_prefix="final")
        if trainer.is_world_process_zero():
            print(final_metrics)


if __name__ == "__main__":
    cli_args = parse_cli_args()
    for current_model_name in cli_args.models:
        _run_single_model(current_model_name)
